win32: fix error C7555: use of designated initializers requires at least '/std:c++latest'  (after commit to rem: 11a1bcfffda095d3187662809fdeacedb9ec72a3)