release v2.8.0 (#552)
* Update README.md (#503)

* thread: fix win32 thrd_create return values (#506)

* cmake: bump min. version 3.10 (#504)

* cmake: add USE_JBUF option (#507)

* tcp: add tcp_send_queued to check queue used

* http: add http_client_set_bufsize_max / http_client_get_bufsize_max

* http, httpauth, websock: support large req body and add body handler

Support large req body.
Allow set body handler.
Use type mbuf for body parameter.

* http/client: fix possible null pointer dereference

Reported-by: Coverity Scan

* ci/windows: test choco install no-progress (#510)

* bitv: remove deprecated module (#513)

* types,fmt: use re_restrict (#514)

Adds `__restrict` macro for WIN32

* sip: refer out of dialog (#508)

* sip: add UAS authentication

* sip: improve err handling for UAS auth

Fixes also a clang analyzer warning "call argument uninitialized".

* readme: update supported versions

* sipsess/update: bugfix (#516)

* sipsess: fix UPDATE issues

In modify.c:sipsess_update() sess->req containing the original INVITE
request was overwritten with the UPDATE request which could lead to a
multitude of problems.

Now, an UPDATE is sent by allocating a sipsess_request and sending it is
handled separately from re-INVITEs.

* sipsess: UPDATE improvements

Remove unused parameters from sipsess_update and correct conditional
checks in sipsess_modify.

* sip/auth: fix mem_zalloc return check (#518)

* ci/clang-analyze: use clang 14

* Update media fixes (#515)

* sipsess: call answer handler for each SDP answer (#2074)

* dns: add dnsc_getaddrinfo_enabled

* http: query getaddrinfo enabled in http_client_set_config

* tmr: Added a method to obtain a realtime clock time point.

Realtime clock time is useful for calculating NTP time points for
RTCP SRs. Applications may use this function to associate RTP
timestamps of sent RTP packets with realtime clock time points,
so that this association is subsequently used to calculate NTP time
points in RTCP SRs.

* rtp: Synchronize NTP and RTP timestamps in RTCP SR.

Obtain the wallclock time once and convert it to both NTP and RTP timestamps
instead of obtaining the current time twice, separated with a mutex lock.
This improves media synchronization quality.

Also, when no RTP packets have been sent and no reference timestamps are
available, generate RR instead of SR to avoid sending bogus timestamps
in the SR.

* rtp: Add realtime timestamps to rtp_send and rtcp_sess_tx_rtp methods.

The realtime timestamps allow the application to specify the time point
that corresponds to the RTP timestamp on the media presentation timeline.
This can be called "capture time", for whatever definition of "capturing"
the application has.

This timestamp is further used to calculate the NTP/RTP timestamps that
are sent in RTCP SR and used on the receiver to synchronize different
media streams from the sender. Having the timestamp provided by the
application allows for a more precise correspondence between NTP and RTP
timestamps, even if the media is sent non-monotonically and out-of-order.

* conf: check if returned size is larger than buffer

* udp: remove very old iOS hack

* tcp: remove very old iOS hack

* cmake,debian: Use CMake for debian packages (#522)

* crc32: add re wrapper (#526)

* ci: convert valgrind to cmake (#529)

* ci: convert valgrind to cmake

* valgrind: use cmake build

* valgrind: minor fixes

* valgrind: build rem with cmake

* coverage: enable verbose retest

* ci: convert ssl build to cmake (#530)

* ci: convert fedora to cmake (#531)

* ci: convert coverage to cmake (#532)

* ci: migrate to cmake (#533)

* ci: migrate to cmake

* run scan-build-14 twice

* cmake: add LINKLIBS and make backtrace and zlib optional (#534)

* cmake: add LINKLIBS and make backtrace and zlib optional

* fix darwin libs

* shim: use try_into_u16_from_size instead generic helper

fixes #520

* atomic,convert: check C11 compatibility

* pcp: fix cppcheck warning

src/pcp/request.c:115:13: warning: Possible null pointer dereference: msg [nullPointer]
 if (err || msg->hdr.result != PCP_SUCCESS ) {
            ^
src/pcp/request.c:141:29: note: Calling function 'completed', 3rd argument 'NULL' value is 0
  completed(req, ETIMEDOUT, NULL);
                            ^
src/pcp/request.c:115:13: note: Null pointer dereference
 if (err || msg->hdr.result != PCP_SUCCESS ) {
            ^

* fmt/print: fix cppcheck overflow

```
src/fmt/print.c:77:15: error: Pointer arithmetic overflow; 'buf' buffer size is 64 [ctuPointerArith]
 char c, *p = buf + NUM_SIZE - 1;
              ^
src/fmt/print.c:272:20: note: Calling function local_itoa, 1st argument is uninitialized
   len = local_itoa(num, (sn < 0) ? -sn : sn, base,
                   ^
src/fmt/print.c:77:15: note: Using argument buf
 char c, *p = buf + NUM_SIZE - 1;
```

* tls: remove SHA1 fingerprint (deprecated)

* telev: add telev_is_empty()

* telev: make parameter const and add NULL pointer check

* debian: release build

* sipreg: avoid sending un-REGISTER periodically

A periodic un-REGISTER should be done only if `fbregint` (fallback SIP server
registration interval) was set.

* cmake,mk: bump the tentative next release with pre-release identifier

* sipsess/update: Add Contact header to UPDATE

UPDATEs are now sent with Contact header which is mandatory according to
RFC 3311.

* cmake: fix shared API soversion (aligned with make)

* cmake/pkgconfig: fix name

* releasae v2.8.0 (#551)

Co-authored-by: Alfred E. Heggestad <alfred.heggestad@gmail.com>
Co-authored-by: Sebastian Reimers <hallo@studio-link.de>
Co-authored-by: Franz Auernigg <f.auernigg@commend.com>
Co-authored-by: Maximilian Fridrich <m.fridrich@commend.com>
Co-authored-by: Andrey Semashev <andrey.semashev@gmail.com>